# Generated by Django 4.2.7 on 2025-05-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_chatparticipant_chatroom_chatparticipant_chat_room_and_more'),
    ]

    operations = [
    ]
