# Generated by Django 4.2.7 on 2025-06-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_menuitem_image_menuitem_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_name',
            field=models.CharField(blank=True, default='img/default-restaurant.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(blank=True, default='img/default-restaurant.jpg', max_length=100),
        ),
    ]
