# Generated by Django 4.2.21 on 2025-05-13 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='用餐日期')),
                ('restaurant_name', models.CharField(max_length=100, verbose_name='餐廳名稱')),
                ('item', models.CharField(max_length=100, verbose_name='品項')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='價格')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='評分')),
                ('mood', models.CharField(choices=[('happy', '開心'), ('soso', '普通'), ('sad', '難過'), ('angry', '生氣'), ('surprised', '驚訝')], max_length=20, verbose_name='心情標籤')),
                ('comment', models.TextField(blank=True, verbose_name='心得')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='checkin_photos/', verbose_name='照片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
