# Generated by Django 4.2.21 on 2025-05-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='經度'),
        ),
    ]
