# Generated by Django 4.2.7 on 2025-05-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ALLERGY', '過敏原'), ('DIET', '飲食習慣'), ('TASTE', '口味偏好')], max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField(help_text='以克為單位')),
                ('carbs', models.FloatField(help_text='以克為單位')),
                ('fat', models.FloatField(help_text='以克為單位')),
                ('fiber', models.FloatField(blank=True, help_text='以克為單位', null=True)),
                ('sugar', models.FloatField(blank=True, help_text='以克為單位', null=True)),
                ('sodium', models.FloatField(blank=True, help_text='以毫克為單位', null=True)),
                ('menu_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='restaurants.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compatible', models.BooleanField(default=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='restaurants.menuitem')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='food_analysis.foodpreference')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='food_analysis.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='restaurants.menuitem')),
            ],
        ),
    ]
