# Generated by Django 4.2.7 on 2025-05-14 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.FloatField(blank=True, help_text='以克為單位', null=True)),
                ('carbs', models.FloatField(blank=True, help_text='以克為單位', null=True)),
                ('fat', models.FloatField(blank=True, help_text='以克為單位', null=True)),
                ('fiber', models.FloatField(blank=True, help_text='以克為單位', null=True)),
                ('sugar', models.FloatField(blank=True, help_text='以克為單位', null=True)),
                ('sodium', models.FloatField(blank=True, help_text='以毫克為單位', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_food_images/')),
                ('date_consumed', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=50)),
                ('food_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='food_analysis.userfoodrecord')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_food_records', to='food_analysis.ingredient')),
            ],
        ),
    ]
