# Generated by Django 4.2.7 on 2025-05-22 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_analysis', '0002_userfoodrecord_userfoodingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfoodrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFoodIngredient',
        ),
        migrations.DeleteModel(
            name='UserFoodRecord',
        ),
    ]
