# Generated by Django 4.2.20 on 2025-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='emotion_tag',
            field=models.CharField(default='普通', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin',
            name='item',
            field=models.CharField(default='未填寫', max_length=100),
        ),
        migrations.AddField(
            model_name='checkin',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(),
        ),
    ]
